#!/usr/bin/env node
var cp = require('./utils/child-process-wrapper.js');
var fs = require('fs');
var path = require('path');
var os = require('os');

var removeCommand = process.platform === 'win32' ? 'rmdir /S /Q ' : 'rm -rf ';

process.chdir(path.dirname(__dirname));
var home = process.env[(process.platform === 'win32') ? 'USERPROFILE' : 'HOME'];

var commands = [
  [__dirname, '..', 'node_modules'],
  [__dirname, '..', 'build', 'node_modules'],
  [__dirname, '..', 'ppm', 'node_modules'],
  [home, '.popcorntime']
];

var run = function() {
  var next = commands.shift();
  if (!next)
    process.exit(0);

  if (Array.isArray(next)) {
    var pathToRemove = path.resolve.apply(path.resolve, next);
    if (fs.existsSync(pathToRemove))
      next = removeCommand + pathToRemove;
    else
      return run();
  }

  cp.safeExec(next, run);
};

run();
