#!/usr/bin/env node
var cp = require('./utils/child-process-wrapper.js');
var fs = require('fs');
var path = require('path');
var os = require('os');

var removeCommand = process.platform === 'win32' ? 'rmdir /S /Q ' : 'rm -rf ';
var productName = require('../package.json').name;

process.chdir(path.dirname(__dirname));
var home = process.env[(process.platform === 'win32') ? 'USERPROFILE' : 'HOME'];
var tmpdir = os.tmpdir();

var killatom = process.platform === 'win32' ? 'START taskkill /F /IM ' + productName + '.exe' : 'pkill -9 ' + productName + ' || true';

var commands = [
  killatom,
  [__dirname, '..', 'node_modules'],
  [__dirname, '..', 'build', 'node_modules'],
  [__dirname, '..', 'ppm', 'node_modules'],
  [home, '.popcorntime', '.node-gyp'],
  [home, '.popcorntime', '.npm']
];
var run = function() {
  var next = commands.shift();
  if (!next)
    process.exit(0);

  if (Array.isArray(next)) {
    var pathToRemove = path.resolve.apply(path.resolve, next);
    if (fs.existsSync(pathToRemove))
      next = removeCommand + pathToRemove;
    else
      return run();
  }

  cp.safeExec(next, run);
};
run();
